### ISSUE TITLE
Installer reboots at 12 minutes remaining

### ISSUE THREAD

**Issue by vicshacks** [icaros7/OpenCore_Surface_Pro_4#1] opened 2021-05-20 19:31 UTC
hey, today i've tried installing Big Sur 11.3 (with the offline installer) with your repo; i have your exact same configuration of the surface pro 4 and i can succesfully boot and start the installation. but once it gets at halfway through (12 minutes remaining) it performs a reboot.

after that, in the OC menu there's both the USB install option and the "macOS installer" option. 

selecting the first one results in the same thing: installation rebooting at 12 minutes remaining.
slecting the other one, theres first an Apple logo with progress bar which reboots into a verbose screen that After about 5 minutes shuts down the machine.

am i doing something wrong with the installation or is there some sort of solution ?

**Comment by icaros7** [comment] 2021-05-21 06:55
In my case, I can re-install normally with latest version of this repo.

I guess carefully, disk partitioning problem. When I install macOS at first time with @bigsadan's OpenCore, I had a same problem.
That was because of partition, and I solved it by backing up the entire disk and re-partitioning it on macOS.

**Comment by icaros7** [comment] 2021-06-01 10:05
This issue will be closed in a few days as no additions things for over 10 days.

**Comment by scylscyl** [comment] 2021-06-02 12:07
I have the same problem. My hard drive is samsung 256GB. 
Repartitioning the entire disk and it on macOS did not work.

**Comment by icaros7** [comment] 2021-06-02 14:11
@scylscyl Let me know what your partitioning step. I will follow you that same step.

By the way, Is that right you've generated Platforminfo?

**Comment by scylscyl** [comment] 2021-06-03 04:19
I formatted the whole disk with hf+ journaling for disc utility. 
I didn't create platforminfo, can you help?

**Comment by icaros7** [comment] 2021-06-03 05:13
@scylscyl This OpenCore config.plist doesn't has platforminfo. I was update [readme.md](https://github.com/icaros7/OpenCore_Surface_Pro_4#english) that include more emphasis about platforminfo.

Checkout that link or follow this [Official OpenCore Guide about platforminfo](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/skylake.html#platforminfo) away.

**Comment by icaros7** [comment] 2021-06-03 05:17
I updated include random generated platforminfo though [GenSMBIOS](https://github.com/corpnewt/GenSMBIOS) for prevent this issue. fe2eddc

**Comment by vicshacks** [comment] 2021-06-03 07:17
> I have the same problem for Big Sur 11.3.1. My hard drive is samsung 256GB.
> Repartitioning the entire disk and it on macOS did not work.

for me, the problem was actually non existent, i Just continued rebooting from macOS and eventually i got to the setup screen.

**Comment by scylscyl** [comment] 2021-06-04 06:54
I updated the platform information. But the same problem persists. 
Attached is the config I used.

[config.zip](https://github.com/icaros7/OpenCore_Surface_Pro_4/files/6596323/config.zip)

**Comment by scylscyl** [comment] 2021-06-04 11:01
> I updated the platform information. But the same problem persists.
> Attached is the config I used.
> 
> [config.zip](https://github.com/icaros7/OpenCore_Surface_Pro_4/files/6596323/config.zip)

Installer reboots at 12 minutes remaining, foto is attached.
![foto](https://user-images.githubusercontent.com/85232305/120791797-b11fd200-c545-11eb-874d-ff1f8ec73855.jpeg)

**Comment by icaros7** [comment] 2021-06-04 11:39
> > I updated the platform information. But the same problem persists.
> > Attached is the config I used.
> > [config.zip](https://github.com/icaros7/OpenCore_Surface_Pro_4/files/6596323/config.zip)
> 
> Installer reboots at 12 minutes remaining, foto is attached.
> ![foto](https://user-images.githubusercontent.com/85232305/120791797-b11fd200-c545-11eb-874d-ff1f8ec73855.jpeg)

@scylscyl Actually I can't find any problem in your log with my knowledge.
And in my hackintosh life If I face installing problem, it mostly cause from disk problem. It might be a bootloader or hardware problem. But if that is problem thought the installation window will not appear.

So I only can tell you, "How to solve in my case"...I'm so sorry for this situation 😢 
If you can format of your all data (include all partition), try to follow this step.

1. Preparing "Windows 10 install USB" (Because I don't know `diskutil` command)
2. Run `Command prompt` via press `Shift + F10`
3. Type next command

> diskpart
> list disk // To see disk number of surface disk
> sel disk n // `n` is your disk number
> clean
> convert gpt
> create part EFI size=200 // `200` is size of EFI partition. I strongly recommend to set more than 200(MB)
> format fs=FAT32 label="SYSTEM" quick

4. Boot to macOS installer than run `Disk Utility` and set up your new partition
5. I will cross my finger for you!

**Comment by scylscyl** [comment] 2021-06-07 04:58
Hi...
Thanks for all your efforts. 
I did everything you wrote but the problem is still the same. 
The last thing I can think of is to share the image file you are using. Let me experience this too

**Comment by icaros7** [comment] 2021-06-08 18:00
[This file](https://drive.google.com/file/d/12kecH_jebWhvZk2jDPWo2nQHte0PwcO3/view?usp=sharing) (Google Drive) is copy of my EFI partition. (include all file like theme, Windows or Android boot entry, etc... / exclude serial)

1. boot to [Super-UEFIinSecureBoot-Disk](https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk) for use Secure Boot.
2. After a few seconds, Will boot into rEFInd
3. Select center item as call "macOS 11 Big Sur"
4. Then boot into OpenCore. (Attention! Auto-pick timeout is 1sec)
5. Before boot into macOS, Press Cmd+V to enable verbose
6. Boot into macOS with OpenCore
7. Fingers crossed

**Comment by scylscyl** [comment] 2021-06-09 04:16
Hello...
The link you gave is problematic, if you give another link.
Thanks

**Comment by icaros7** [comment] 2021-06-09 05:22
> Hello...
> The link you gave is problematic, if you give another link.
> Thanks

[New Link (Google Drive)](https://drive.google.com/file/d/1worxDrhZNW5bKT01vx3KIEkYV8-5t0s4/view?usp=sharing). Sry for gave wrong link.

**Comment by scylscyl** [comment] 2021-06-09 05:32
> > Merhaba... 
> > Verdiğiniz link sorunlu, başka link verirseniz sorun olur. 
> > Teşekkürler
> 
> [Yeni Bağlantı (Google Drive)](https://drive.google.com/file/d/1worxDrhZNW5bKT01vx3KIEkYV8-5t0s4/view?usp=sharing) . Sry için yanlış bağlantı verdi.

As far as I understand, Google blocks it. If you upload an encrypted rar file or to a different platform, it will be a solution.

**Comment by icaros7** [comment] 2021-06-09 05:49
> > > Merhaba...
> > > Verdiğiniz link sorunlu, başka link verirseniz sorun olur.
> > > Teşekkürler
> > 
> > 
> > [Yeni Bağlantı (Google Drive)](https://drive.google.com/file/d/1worxDrhZNW5bKT01vx3KIEkYV8-5t0s4/view?usp=sharing) . Sry için yanlış bağlantı verdi.
> 
> As far as I understand, Google blocks it. If you upload an encrypted rar file or to a different platform, it will be a solution.

Oh, I can see also the problem in private browsing mode.

I uploaded with password `Surface`
[Google Drive](https://drive.google.com/file/d/1_behMYncyAJMzJAwXWlnGelQKzzq9KHd/view?usp=sharing) or [My own nas](https://nws.harukasan.org:5001/sharing/C7QwgwLhx)

**Comment by scylscyl** [comment] 2021-06-09 06:50
> > > Merhaba...
> > > Verdiğiniz link sorunlu, başka link verirseniz sorun olur.
> > > Teşekkürler
> > 
> > 
> > [Yeni Bağlantı (Google Drive)](https://drive.google.com/file/d/1worxDrhZNW5bKT01vx3KIEkYV8-5t0s4/view?usp=sharing) . Sry için yanlış bağlantı verdi.
> 
> As far as I understand, Google blocks it. If you upload an encrypted rar file or to a different platform, it will be a solution.

Thanks, I got the file, I'll try and let you know.

**Comment by scylscyl** [comment] 2021-06-10 04:35
Hello...
Thank you very much for your interest.
I edited the EFI you gave for my computer.
I did everything you said but it still hangs in the same place. I couldn't find what the problem is.

> ~This file (Google Drive)~ is copy of my EFI partition. (include all file like theme, Windows or Android boot entry, etc... / already changed serial num to another serial)
> 
> 1. boot to [Super-UEFIinSecureBoot-Disk](https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk) for use Secure Boot.
> 2. After a few seconds, Will boot into rEFInd
> 3. Select center item as call "macOS 11 Big Sur"
> 4. Then boot into OpenCore. (Attention! Auto-pick timeout is 1sec)
> 5. Before boot into macOS, Press Cmd+V to enable verbose
> 6. Boot into macOS with OpenCore
> 7. Fingers crossed

Hello...
Thank you very much for your interest.
I edited the EFI you gave for my computer.
I did everything you said but it still hangs in the same place. I couldn't find what the problem is.

**Comment by icaros7** [comment] 2021-06-10 09:23
@scylscyl Well....Now I don't know, How do I hand for you...

What about install image? I download macOS from [part of this official OpenCore Guide](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/) via Windows 10.

**Comment by scylscyl** [comment] 2021-06-11 06:04
Hi..
Thank you so much for your support and patience. 
I have completed the installation. After a few tries, I'll write where I got stuck and how I got the result. 

-Can you suggest a wifi and bluetooth device that i can use.
-Horndis doesn't work. Is there a way to get it working?
-If boot-args remove "-v" boot fails.
-Is it possible to change the default language?
Have a nice day.

**Closed** 2021-06-13 16:35 UTC
Labels: enhancement, install-problem, surface-pro-4
